openapi: 3.1.0
info: {title: Deploy API, version: 1.0.0}
servers: [{url: https://api.netlify.com}]
paths:
  /build_hooks/{hook_id}:
    post:
      operationId: triggerNetlifyBuildHook
      parameters:
        - name: hook_id
          in: path
          required: true
          schema: {type: string}
      responses: {'200': {description: ok}}
